### PR TITLE
ru_ru localization

### PR DESCRIPTION
**Pull request by Hardziplay**

### CODE REVIEW

**Review by VladisCrafter — CHANGES_REQUESTED** [review]
Overall the translation is really good (not even Google-translated, shocking). Although I would request some tweaks here:
- Different name of a block and its slab. Take a look at netherrack, for example: "cut netherrack" and its slab already has "bricks" in it! Strange;
- Catalyst should probably be translated as "катализатор" for vanilla parity;
- Blueprint blocks: "блок чертежей" {block of blueprints} sounds odd, "чертёжный блок" might be a better solution.

Thanks for reading and hope you have a great day. And good luck translating this and other stuff :]

**Comment by Hardziplay** [comment]
image
Netherack blocks are fine as i see

**Comment by Hardziplay** [comment]
They are just in alphabetic order

**Comment by VladisCrafter** [comment]
Oooh, alphabetic order... I didn't notice this, my bad I'm sorry 😅 
What about other issues tho?

**Comment by Hardziplay** [comment]
I'll fix them if this gets merged with main branch

**Comment by LopyLuna** [comment]
will merge tmr

**Comment by VladisCrafter** [comment]
"tmr" 😀👍

**Comment by VladisCrafter** [comment]
Soo when blueprint blocks and catalyst fixes @Hardziplay? :>

**Pull request merged**
